apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.applicationName }}-api-service
  namespace: jonathanlee-io-{{ .Values.environment.name }}
  labels:
    app: {{ .Values.applicationName }}
    chart: {{ template "jonathanlee-io.chart" . }}
    component: "{{ .Values.api.name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.api.port }}
    targetPort: {{ .Values.api.port }}
{{- if eq .Values.environment.name "development" }}
    nodePort: {{ .Values.api.service.nodePort }}
  type: NodePort
{{- end }}
  selector:
    app: {{ template "jonathanlee-io.fullname" . }}
    component: "{{ .Values.api.name }}"
    release: {{ .Release.Name }}
