apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "jonathanlee-io.fullname" . }}-ui-deployment
  namespace: jonathanlee-io-{{ .Values.environment.name }}
  labels:
    app: {{ template "jonathanlee-io.fullname" . }}
    chart: {{ template "jonathanlee-io.chart" . }}
    component: "{{ .Values.ui.name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "jonathanlee-io.fullname" . }}
      component: "{{ .Values.ui.name }}"
      release: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ template "jonathanlee-io.fullname" . }}
        component: "{{ .Values.ui.name }}"
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "jonathanlee-io.fullname" . }}-ui
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          imagePullPolicy: "{{ .Values.ui.image.pullPolicy }}"
          livenessProbe:
            httpGet:
              port: 80
              path: /
            initialDelaySeconds: 3
            periodSeconds: 3
      restartPolicy: Always
status: {}
