applicationName: jonathanlee-io
replicaCount: 1

environment:
  name: development
  hostPrefix: development.

ui:
  name: ui
  image:
    repository: jonathanleedev/jonathanlee.io
    tag: latest
    pullPolicy: Never
  service:
    type: NodePort
    nodePort: 30001
  port: 80

api:
  name: api
  image:
    repository: jonathanleedev/contact-node
    tag: latest
    pullPolicy: Never
  service:
    type: NodePort
    nodePort: 30002
  port: 8080
