applicationName: jonathanlee-io
replicaCount: 1

environment:
  name: production
  hostPrefix:

ui:
  name: ui
  image:
    repository: jonathanleedev/jonathanlee.io
    tag: latest
    pullPolicy: Always
  port: 80

api:
  name: api
  image:
    repository: jonathanleedev/contact-node
    tag: latest
    pullPolicy: Always
  port: 8080
